name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *" # Ejecutar cada 6 horas
  workflow_dispatch: # Permite la ejecución manual desde la interfaz de GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main # O la rama principal de tu repositorio

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Dev-IvanNumpaque # ¡Asegúrate de que este sea tu nombre de usuario!
          outputs: dist/github-contribution-grid-snake.svg?palette=github-dark
          # Puedes personalizar la apariencia aquí (colores, tema, etc.)

      - name: Add generated file
        run: |
          git add dist/github-contribution-grid-snake.svg

      - name: Commit changes
        run: |
          git config --local user.email "Dev-IvanNumpaque@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Generate snake animation"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true # Puede ser necesario si la rama 'output' ya existe
